#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR"/vars
echo "./provision_cicd.sh -p <PROJECT_ID> [-c <CLUSTER>]  [-s <SERVICE_ACCOUNT>]  - for Gitlab CI/CD Integration"
echo "./provision_demo.sh -p <PROJECT_ID> [-c <CLUSTER>]                          - for Manual DEMO deployment"
echo ""
echo "Defaults:"
echo "   PROJECT_ID=$PROJECT_ID"
echo "   CLUSTER=$CLUSTER"
echo "   SERVICE_ACCOUNT=$SERVICE_ACCOUNT"
echo "   ZONE=$ZONE"
echo "   REGION=$REGION"
echo "   ARGOLIS=$ARGOLIS"

