#!/usr/bin/env bash

ZONE=${ZONE:-'us-central1-c'}
REGION=${REGION:-'us-central1'}
NETWORK=${NETWORK:-'drls'}
CLUSTER=${CLUSTER:-'prior-auth'}
MACHINE_TYPE=${MACHINE_TYPE:-'e2-standard-8'}
SERVICE_ACCOUNT=${SERVICE_ACCOUNT:-${CLUSTER}'-gitlab-sa'}
CLUSTER_VERSION='1.21.10-gke.2000'

